app:
  password: P@ssW0rd
  keystoreAlias: pdfsigning
spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      fail-on-empty-beans: false
  freemarker:
    suffix: .ftlh
    cache: false
    template-loader-path:
      - classpath:/templates/
